export const FE_PATH = {
  ORIGIN: "http://localhost:3000",
  HOME: "/home",
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  ADMIN: "/admin",
  NEWS: "/blogs",
  NEWS_DETAIL: "/blogs/:id",
  USER: "/users",
  BUY_TICKET: "/buy-ticket",
  ORDER: "/order",
  MY_TICKETS: "/my-tickets",
  METRO_MAP: "/metro-map",
  PAYMENT_SUCCESS: "/payment/success",
  PAYMENT_FAILURE: "/payment/failure",
  SOCIAL_LOGIN_REDIRECT: "/oauth2/redirect",
  PROFILE: "/profile",
  VERIFY_REQUEST: "/admin/requests",
  MANAGE_FEEDBACK: "/admin/feedbacks",
} as const;

export const API_PATH = {
  ORIGIN: "http://localhost:4003/api",
  GOOGLE_LOGIN: `http://localhost:4003/api/oauth2/authorization/google`,
  FACEBOOK_LOGIN: `http://localhost:4003/api/oauth2/authorization/facebook`,
  LOGOUT: "/auth/logout",
  LOCAL_LOGIN: "/auth/local-login",
  BLOG: "http://localhost:4007/api/v1/users/blogs",
  STATIONS: "http://localhost:4003/api/stations",
  SCHEDULES: "http://localhost:4003/api/schedules",
  ROUTE: "http://localhost:4003/api/routes",
  TICKET: "http://localhost:4003/api/ts/tickets",
  TICKETTYPE: "http://localhost:4003/api/ts/ticket-types",
  TICKETUSAGE: "http://localhost:4003/api/ts/ticket-usage-logs",
  FARE: "http://localhost:4003/api/ts/fare-matrices",
  ORDER: "http://localhost:4003/api/orders",
  PAYMENT: "http://localhost:4003/api/orders/payment-methods",
  VNPAY: "http://localhost:4003/api/payment",
  PAYPAL: "http://localhost:4003/api/payment/paypal",
  BUS: "http://localhost:4003/api/bus",
} as const;
